Test/if else diffif
programming-language-ravenclaw/Ravenclaw pull request #15
Opened 2024-06-24 01:59 UTC by saletG08

- [X] Hacer todos los casos posibles de la palabra reservada de If-else-diffif
- [X] Dividirlo en carpeta para hacer mas limpio el codigo

2024-06-24 16:49 UTC, LuchoVera1 requested changes

2024-06-24 16:49 UTC, LuchoVera1 commented on test/Statement/ConditionalStatement/ConditionalStatementTest.hs
> +    show result `shouldBe` "Left (line 1, column 1):\nunexpected 'd'\nexpecting white space, \"while\", \"for\", \"if\", \"int\", \"float\", \"bool\", \"str\", \"list\", digit, \"\\\"\", \"true\", \"
El test falla dado al añadido de metodos en lo esperado

```
       expected: Left (line 1, column 1):
                 unexpected 'd'
                 expecting white space, "while", "for", "if", "int", "float", "bool", "str", "list", digit, "\"", "true", "false", "[", "print", "#", "##" or end of input
        but got: Left (line 1, column 1):
                 unexpected 'd'
                 expecting white space, "while", "for", "if", "int", "float", "bool", "str", "list", digit, "\"", "true", "false", "[", "print", "#", "##", "method" or end of input
```

2024-06-24 16:49 UTC, LuchoVera1 commented on test/Statement/ConditionalStatement/ConditionalStatementTest.hs
> +    show result `shouldBe` "Left (line 1, column 1):\nunexpected 'e'\nexpecting white space, \"while\", \"for\", \"if\", \"int\", \"float\", \"bool\", \"str\", \"list\", digit, \"\\\"\", \"true\", \"
Mismo caso que el anterior test fallido por el mensaje

```
test/Statement/ConditionalStatement/ConditionalStatementTest.hs:57:17: 
  2) parses if statements detects error in else statement without an if or if-diffif before the condition
       expected: Left (line 1, column 1):
                 unexpected 'e'
                 expecting white space, "while", "for", "if", "int", "float", "bool", "str", "list", digit, "\"", "true", "false", "[", "print", "#", "##" or end of input
        but got: Left (line 1, column 1):
                 unexpected 'e'
                 expecting white space, "while", "for", "if", "int", "float", "bool", "str", "list", digit, "\"", "true", "false", "[", "print", "#", "##", "method" or end of input

```

2024-06-24 19:55 UTC, saletG08 commented on test/Statement/ConditionalStatement/ConditionalStatementTest.hs
> +    show result `shouldBe` "Left (line 1, column 1):\nunexpected 'd'\nexpecting white space, \"while\", \"for\", \"if\", \"int\", \"float\", \"bool\", \"str\", \"list\", digit, \"\\\"\", \"true\", \"
done

2024-06-24 19:55 UTC, saletG08 commented on test/Statement/ConditionalStatement/ConditionalStatementTest.hs
> +    show result `shouldBe` "Left (line 1, column 1):\nunexpected 'e'\nexpecting white space, \"while\", \"for\", \"if\", \"int\", \"float\", \"bool\", \"str\", \"list\", digit, \"\\\"\", \"true\", \"
done

2024-06-25 00:32 UTC, LuchoVera1 approved these changes

2024-06-25 00:32 UTC, merged