test for DataTypeDeclaration
programming-language-ravenclaw/Ravenclaw pull request #16
Opened 2024-06-24 03:19 UTC by LuchoVera1

2024-06-24 04:54 UTC, saletG08 requested changes

2024-06-24 16:17 UTC, LuchoVera1 commented on test/Statement/DataTypeDeclarationParserTest.hs
> +
Se añadieron todos los casos sugeridos

2024-06-25 19:01 UTC, saletG08 requested changes

2024-06-25 19:01 UTC, saletG08 commented on test/Spec.hs
> +import Statement.DataDeclaration.DataTypeDeclarationParserTest (testParseDataTypeDeclaration)
No es necesario poner el (testParseDataTypeDeclaration) puedes borrarlo eso.

2024-06-25 19:09 UTC, saletG08 requested changes

2024-06-25 19:09 UTC, saletG08 commented on test/Statement/DataDeclaration/DataTypeDeclarationParserTest.hs
> +isLeft :: Either a b -> Bool
en vez de utilizar uno de esto podria llamar a la libreria de import Data.Either eso te ayudara

2024-06-26 15:06 UTC, saletG08 approved these changes

2024-06-26 15:06 UTC, merged