Added documentation for Loops and Conditionals
programming-language-ravenclaw/Ravenclaw pull request #22
Opened 2024-06-25 02:05 UTC by LuchoVera1

2024-06-26 15:18 UTC, RonaldoMendozaM commented on src/Statement/StatementParser.hs
> +-- This function is used to parse diff-if statements
te faltaría añadir un ejemplo a tu documentación

2024-06-26 15:19 UTC, ronaldo-mendoza-jalafund requested changes
Falta añadir ejemplos

2024-07-05 08:12 UTC, gabygabylagaby approved these changes

2024-07-05 08:12 UTC, gabygabylagaby commented
Good job.

2024-07-05 08:14 UTC, merged