Method call recognition, tests, Documentation and Error Handling
programming-language-ravenclaw/Ravenclaw pull request #23
Opened 2024-06-25 02:43 UTC by EmanuelGalindoC

2024-06-25 03:12 UTC, LuchoVera1 requested changes

2024-06-25 03:12 UTC, LuchoVera1 commented on resources/code.rvc
> +methodCall(1, 2, )
Hay un error al momento de correr el codigo

```
(line 225, column 12):
unexpected "1"
expecting white space, "int", "float", "bool", "str" or "list"
```

2024-06-25 03:31 UTC, EmanuelGalindoC commented on resources/code.rvc
> +methodCall(1, 2, )
Solved

2024-06-25 03:58 UTC, LuchoVera1 requested changes

2024-06-25 03:58 UTC, LuchoVera1 commented on test/Methods/MethodCallParserTest.hs
> +testMethodCallParser :: Spec
Los Tests fallan

```
Finished in 0.0887 seconds
73 examples, 30 failures
                       


Ravenclaw> Test suite Ravenclaw-test failed
Completed 2 action(s). 

Error: [S-7282]
       Stack failed to execute the build plan.
       
       While executing the build plan, Stack encountered the error:
       
       Error: [S-1995]
       Test suite failure for package Ravenclaw-0.1.0.0
           Ravenclaw-test:  exited with: ExitFailure 1
       Logs printed to console
       
```

2024-06-26 13:30 UTC, LuchoVera1 requested changes, later dismissed

2024-06-26 13:30 UTC, LuchoVera1 commented on resources/code.rvc
> +else { }
Hay un error al momento de hacer el stack run

```
Registering library for Ravenclaw-0.1.0.0..
(line 226, column 5):
unexpected ()
expecting letter or digit
```

2024-06-26 13:30 UTC, LuchoVera1 commented on src/Expression/ExpressionParser.hs
> +expression = try (ArithmeticExpr <$> arithmeticExpression)
Porque se añaden try a cada caso?

2024-06-26 13:30 UTC, LuchoVera1 commented on src/Statement/StatementParser.hs
> -elseStatementParser = Else <$> (string "else" *> spaces *> char '{' *> spaces *> many statement <* spaces <* char '}')
no elimines el endLine de otros archivos

2024-06-26 13:42 UTC, EmanuelGalindoC commented on src/Expression/ExpressionParser.hs
> +expression = try (ArithmeticExpr <$> arithmeticExpression)
Fue una clase de experimento para ver cambios, pero ya no es importante, ya esta arreglado

2024-06-26 13:45 UTC, EmanuelGalindoC commented on src/Statement/StatementParser.hs
> -elseStatementParser = Else <$> (string "else" *> spaces *> char '{' *> spaces *> many statement <* spaces <* char '}')
Es posible que sea un error de github porque no existe cambios alli

2024-06-29 20:38 UTC, saletG08 requested changes

2024-06-29 20:38 UTC, saletG08 commented on src/Expression/ExpressionParser.hs
> -listExpression = ListExpr <$> (spaces *> char '[' *> spaces *> expression `sepBy` (spaces *> char ',' <* spaces) <* spaces <* char ']' <* spaces)
Porque parece como si hubieras eliminado y añadido otra vez?, no veo ningun cambio que hiciste.

2024-06-29 20:38 UTC, saletG08 commented on src/Expression/ExpressionParser.hs
> +methodCallParser = do
Trata de hacer con Functor no con do y return, ademas elimina la parte de Handle Errors, anteriormente mencione que estas validaciones se haran en la tabla de simbolos, por ahora no lo necesitamos

2024-06-29 20:38 UTC, saletG08 commented on src/Statement/StatementParser.hs
> +    , try (spaces *> (Comment <$> comment) <* spaces)
Solo aumnetaste un espacio, eso no es un cambio, eliminalo.

2024-06-29 20:38 UTC, saletG08 commented on test/Methods/MethodCallParserTest.hs
> +        parse Expression.ExpressionParser.methodCallParser "" (T.pack "print(1, \"Hello\", true)") `shouldBe`
podrias cambiar el nombre del metodo? ya que el print para nosotros es una palabra reservada, algo que deberia de darte error y no deberia de validar este test.

2024-07-01 00:17 UTC, EmanuelGalindoC commented on src/Expression/ExpressionParser.hs
> -listExpression = ListExpr <$> (spaces *> char '[' *> spaces *> expression `sepBy` (spaces *> char ',' <* spaces) <* spaces <* char ']' <* spaces)
Quiza github tenga un error pero no elimine ni añadi nada alli

2024-07-01 00:23 UTC, EmanuelGalindoC commented on test/Methods/MethodCallParserTest.hs
> +        parse Expression.ExpressionParser.methodCallParser "" (T.pack "print(1, \"Hello\", true)") `shouldBe`
![image](https://github.com/programming-language-ravenclaw/Ravenclaw/assets/101750043/84fb1e73-f13f-4845-a663-3d58b9f3c90d)
Al darle un metodo print como income sale asi:
![image](https://github.com/programming-language-ravenclaw/Ravenclaw/assets/101750043/c20b8b68-b5bf-4ab6-a594-0ff844aca3c0)
El error se debe a que en el test estoy probando exclusivamente al methodCall y a los demas no, por eso la discrepancia, pero eso ya esta solucionado.

2024-07-01 00:27 UTC, EmanuelGalindoC commented on src/Statement/StatementParser.hs
> +    , try (spaces *> (Comment <$> comment) <* spaces)
I guess

2024-07-01 00:50 UTC, EmanuelGalindoC commented on src/Expression/ExpressionParser.hs
> +methodCallParser = do
Done

2024-07-01 03:46 UTC, saletG08 requested changes

2024-07-01 03:46 UTC, saletG08 commented on src/AST/AST.hs
> +                | MethodCallExpr MethodCall
![Captura desde 2024-06-30 22-43-23](https://github.com/programming-language-ravenclaw/Ravenclaw/assets/135137641/b83bdea8-48a5-45c8-ac8e-4747f6caa68a)

Fijate en donde se tiene que hacer el MethodCall en el AST o el BNF

2024-07-02 22:21 UTC, saletG08 requested changes

2024-07-02 22:21 UTC, saletG08 commented on src/Statement/MethodCallParser.hs
> +printerReservedWords :: [String]
Falta documentacion y siento que esto seria bueno que lo pongas dentro de la carpeta de Utils, ya que podemos utilizarlo para otras ocaciones.

2024-07-04 04:55 UTC, saletG08 approved these changes

2024-07-04 04:55 UTC, merged