PrinterSymbolTable
programming-language-ravenclaw/Ravenclaw pull request #35
Opened 2024-07-02 19:56 UTC by RonaldoMendozaM

2024-07-02 22:32 UTC, saletG08 requested changes

2024-07-02 22:32 UTC, saletG08 commented on Ravenclaw.cabal
> +      SymbolTable.SematicAnalyzerPrinter
![Captura desde 2024-07-02 18-31-31](https://github.com/programming-language-ravenclaw/Ravenclaw/assets/135137641/0279d45a-b4cf-4f8e-bfe9-afcd8f4bd531)

me sale error de al compilar.

2024-07-02 22:42 UTC, saletG08 requested changes

2024-07-02 22:42 UTC, saletG08 commented on src/SymbolTable/SematicAnalyzerPrinter.hs
> +processPrinter :: Printer -> SymbolTable -> SymbolTable
y en que parte lo estas llamando para que se pueda imprimir el symbol table para ver los resultados?

2024-07-05 10:06 UTC, RonaldoMendozaM commented
Este feature se trabajo en otra rama

2024-07-05 10:06 UTC, RonaldoMendozaM commented
closed

2024-07-05 10:06 UTC, closed without merging